server:
  port: 8081
  servlet:
    context-path: /luckmoney

limit:
  minMoney: 0.01
  maxMoney: 9999
  description: 最少要发${limit.minMoney}元，最多要发${limit.maxMoney} 元。


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/luckmoney?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 410812

  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create （create表示创建，update表示更新）
    show-sql: true
